// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDVViFAWOqGWMRqA-AXnI89yQExeKJrE',
    appId: '1:580589411646:web:bfcc73db762b3a1689a06f',
    messagingSenderId: '580589411646',
    projectId: 'book-mate-50bbd',
    authDomain: 'book-mate-50bbd.firebaseapp.com',
    storageBucket: 'book-mate-50bbd.appspot.com',
    measurementId: 'G-J38TM0B7JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIzPeh84CXikUu6Lt07ciVgxmXnoqf1w',
    appId: '1:580589411646:android:fce69c52cd58f3d989a06f',
    messagingSenderId: '580589411646',
    projectId: 'book-mate-50bbd',
    storageBucket: 'book-mate-50bbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_eoZAWg0kNqkt_ZUFII6j2fBwWSWXqc',
    appId: '1:580589411646:ios:213767f90276c08589a06f',
    messagingSenderId: '580589411646',
    projectId: 'book-mate-50bbd',
    storageBucket: 'book-mate-50bbd.appspot.com',
    iosClientId: '580589411646-fb2pltj18jb55ikjpaun5uu848nkd14f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_eoZAWg0kNqkt_ZUFII6j2fBwWSWXqc',
    appId: '1:580589411646:ios:a6b762feff9c852e89a06f',
    messagingSenderId: '580589411646',
    projectId: 'book-mate-50bbd',
    storageBucket: 'book-mate-50bbd.appspot.com',
    iosClientId: '580589411646-ub07mu4vp1q9as4qj4hlairj8faug07h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookMate.RunnerTests',
  );
}
